# Generated by Django 3.1.6 on 2021-02-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=25, verbose_name='IP address')),
                ('name', models.CharField(max_length=25, verbose_name='Warehouse name')),
                ('token', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('status', models.CharField(choices=[('New', 'new'), ('In progress', 'in progress'), ('Stored', 'stored'), ('Sent', 'sent')], default='New', max_length=15)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.store')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'abstract': False,
            },
        ),
    ]
