# Generated by Django 3.1.6 on 2021-02-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=25, verbose_name='URL')),
                ('name', models.CharField(max_length=25)),
                ('server_token', models.CharField(blank=True, max_length=25)),
                ('client_token', models.CharField(blank=True, default='', max_length=25)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6, verbose_name='Order number')),
                ('status', models.CharField(
                    choices=[('New', 'new'), ('In progress', 'in progress'), ('Stored', 'stored'), ('Sent', 'sent')],
                    default='New', max_length=15)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeapp.warehouse')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
